add_newline = true
palette = 'dark-gradient-blue-purple'

format = """\
[](fg:os-bg)\
[$os ](bg:os-bg fg:os-fg)\
[](fg:os-bg bg:dir-bg)\
[  ](bg:dir-bg fg:dir-fg)\
$directory\
[](bg:git-branch-bg fg:dir-bg)\
$git_branch\
[](bg:git-status-bg fg:git-branch-bg)\
$git_status\
[](fg:git-status-bg) \
"""

[palettes.gradient-purple]
os-bg = '#370080'         # 
os-fg = '#e6e7ed'         # 
dir-bg = '#5200bf'        # 
dir-fg = '#e6e7ed'        # 
git-branch-bg = '#652f8e' # 
git-branch-fg = '#e6e7ed' # 
git-status-bg = '#7e58b0' # 
git-status-fg = '#e6e7ed' # 

[palettes.gradient-blue-purple]
os-bg = '#1654a6'         # 
os-fg = '#e6e7ed'         # 
dir-bg = '#383a76'        # 
dir-fg = '#e6e7ed'        # 
git-branch-bg = '#50286e' # 
git-branch-fg = '#e6e7ed' # 
git-status-bg = '#5c137d' # 
git-status-fg = '#e6e7ed' # 

[palettes.dark-gradient-blue-purple]
os-bg = '#154789'         # 
os-fg = '#e6e7ed'         # 
dir-bg = '#2e2f58'        # 
dir-fg = '#e6e7ed'        # 
git-branch-bg = '#3e2352' # 
git-branch-fg = '#e6e7ed' # 
git-status-bg = '#4f126c' # 
git-status-fg = '#e6e7ed' #

[palettes.neon]
os-bg = '#965027'         # brown - orange
os-fg = '#ffffff'         # white
dir-bg = '#1D2B53'        # navy
dir-fg = '#ffffff'        # white
git-branch-bg = '#3E065F' # maroon
git-branch-fg = '#ffffff' # white
git-status-bg = '#570530' # red
git-status-fg = '#ffffff' # black
red = 'F90716'            # red

[palettes.pastel]
os-bg = '#5a3e8e'         # purple
os-fg = '#e6e7ed'         # white font
dir-bg = '#006c86'        # blue
dir-fg = '#e6e7ed'        # white
git-branch-bg = '#8f5e15' # orange
git-branch-fg = '#e6e7ed' # white
git-status-bg = '#8c4351' # red
git-status-fg = '#e6e7ed' # black

[palettes.blue]
os-bg = '#3340ff'         # dark blue
os-fg = '#e6e7ed'         # white font
dir-bg = '#525dff'        # blue
dir-fg = '#e6e7ed'        # white
git-branch-bg = '#7079ff' # blue
git-branch-fg = '#e6e7ed' # white
git-status-bg = '#8f96ff' # light blue
git-status-fg = '#e6e7ed' # black

[palettes.bind-light]
dir-bg = '#003161'        # navy
dir-fg = '#ffffff'        # white
git-branch-bg = '#006a67' # teal
git-branch-fg = '#ffffff' # white
git-status-bg = '#fff4b7' # yellow
git-status-fg = '#000000' # black

[palettes.bind-cold]
dir-bg = '#211951'        # navy
dir-fg = '#ffffff'        # white
git-branch-bg = '#836fff' # purple
git-branch-fg = '#ffffff' # white
git-status-bg = '#15f5ba' # mint
git-status-fg = '#000000' # black

[palettes.bind-pastel]
dir-bg = '#8174a0'        # dark-purple
dir-fg = '#ffffff'        # white
git-branch-bg = '#a888b5' # purple
git-branch-fg = '#ffffff' # white
git-status-bg = '#efb6c8' # pink
git-status-fg = '#000000' # black

[username]
style_user = "white bold"
style_root = "black bold"
format = "[$user]($style) "
disabled = true  # disable in powershell
show_always = false

[directory]
style='bold bg:dir-bg fg:dir-fg'
read_only_style='bold bg:dir-bg fg:red'
home_symbol = " ~"
read_only = " "
format = "[$path ]($style)[$read_only]($style)"

[directory.substitutions]
"Documents" = "󰈙 "
"documents" = "󰈙 "
"Downloads" = " "
"downloads" = " "
"Music" = " "
"music" = " "
"Pictures" = " "
"pictures" = " "
"Images" = " "
"images" = " "

[git_branch]
style='bold bg:git-branch-bg fg:git-branch-fg'
symbol = " "
format = "[ $symbol$branch ]($style)"
# truncation_length = 4
# truncation_symbol = "…/"

[git_status]
style='bold bg:git-status-bg fg:git-status-fg'
format = '[ $all_status$ahead_behind]($style)'
conflicted = "󰞇 "
up_to_date = " "
untracked = " "
ahead = "󱦲${count} "
diverged = "󰹺󱦲${ahead_count}󱦳${behind_count} "
behind = "󱦳${count} "
stashed = " "
modified = "󰷫 "
staged = '[++\($count\) ](style)'
renamed = "󰏫 "
deleted = " "

[os]
disabled = false
style = "bold bg:os_bg fg:os_fg"

[os.symbols]
Windows=''
Ubuntu=''
Arch='󰣇'
Debian=''
