##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

windowrule {
    name = pip
    match:initial_title = ^(Picture-in-Picture)$

    float = on
    move = (monitor_w*0.65) (monitor_h*0.65)
    size = (monitor_w*0.3) (monitor_h*0.3)
    pin = on
}

windowrule {
    name = buds
    match:initial_class = ^(GalaxyBudsClient)$

    float = on
    center = on
    size = (monitor_w*0.5) (monitor_h*0.6)
}

windowrule {
    name = file-explorer
    match:initial_class = ^(org.kde.dolphin)$

    float = on
    center =on
    size = (monitor_w*0.6) (monitor_h*0.6)
}

windowrule {
    name = legacy-launcher
    match:initial_class = ^(ru-turikhay-tlauncher-bootstrap-Bootstrap)$

    float = on
    center = on
    size = (monitor_w*0.6) (monitor_h*0.6)
}

windowrule {
    name = tg-media-viewer
    match:initial_class = ^(telegram-desktop_telegram-desktop)$
    match:initial_title = ^(Media viewer)$

    float = on
}

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppress_event maximize, match:class .*

# Fix some dragging issues with XWayland
windowrule = match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0, no_focus 1
