##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

windowrule = float on, move 65% 65%, size 30% 30%, pin on, match:initial_title ^(Picture-in-Picture)$
windowrule = float on, center on, size 60% 60%, match:initial_class ^(GalaxyBudsClient)$
windowrule = float on, center on, size 60% 60%, match:initial_class ^(org.kde.dolphin)$
windowrule = float on, center on, size 60% 60%, match:initial_class ^(ru-turikhay-tlauncher-bootstrap-Bootstrap)$
windowrule = float on, match:initial_class ^(telegram-desktop_telegram-desktop)$, match:initial_title ^(Media viewer)$

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppress_event maximize, match:class .*

# Fix some dragging issues with XWayland
windowrule = match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0, no_focus 1
