# add next line to ~/.bashrc
# source <path/to/this/file>

alias pbcopy='xclip -selection clipboard' # copy to clipboard
alias pbpaste='xclip -selection clipboard -o' # paste from clipboard

alias ls='lsd'
alias tree='lsd --tree -I node_modules -I bin -I obj'
alias grep='grep --color=auto'

alias pgctl='pg_ctl'

alias tnew='tmux new -s $(basename $(pwd))'

export dev=/mnt/shared/dev/
export SUDO_EDITOR=/usr/bin/nvim

export STARSHIP_CONFIG=~/.config/starship/starship.toml
eval "$(starship init bash)"

export FZF_DEFAULT_OPTS='--tmux 80%'
eval "$(fzf --bash --tmux 80%)"

bind 'set completion-ignore-case on'

buds() {
    if [ "$1" = "con" ]; then
        bluetoothctl devices Paired | awk '/Buds/{print $2}' | xargs -I{} bluetoothctl connect {}
        return 0
    elif [ "$1" = "dis" ]; then
        bluetoothctl devices Connected | awk '/Buds/{print $2}' | xargs -I{} bluetoothctl disconnect {}
        return 0
    fi

    echo -e "arguments not understood;\nusage: buds (con|dis)"
    return 1;
}
